10 toast message integration
mertgvcn/Communify-Backend pull request #23
Opened 2024-04-17 14:10 UTC by mertgvcn

Toast messages added. Previous cryption issues fixed.

2024-04-18 12:21 UTC, immrlolled requested changes
General good. Few points you need to fix also few bugs you made .

2024-04-18 12:21 UTC, immrlolled commented on Services/CryptionService.cs
> +            string privatekey = "hgfedcba";
Key and private key in the appsettings mate not here the fuck is this

2024-04-18 12:21 UTC, immrlolled commented on Services/CryptionService.cs
> +        {
Try catching and returning exception message as password decryption? Please remove the try catch. in case of a crash im expecting a throw instead of a return

2024-04-18 12:21 UTC, immrlolled commented on Services/CryptionService.cs
> +    public string Decrypt(string key)
Missing task to await. It can be slow sometimes so it needs to be an awaited function

2024-04-18 12:21 UTC, immrlolled commented on web/src/utils/Cryption.ts
> +    return ex.message;
Returning ex.message as password decryption. Same here as i gave comment on the c# comment.

2024-04-18 12:21 UTC, immrlolled commented on appsettings.json
> +  "Crypto": {
you added it here tho but you dont use it

2024-04-18 12:21 UTC, immrlolled commented on web/src/utils/Cryption.ts
> +  const _key = CryptoJS.enc.Utf8.parse(keyValue);
Expecting promise to await this task.

2024-04-18 12:21 UTC, immrlolled commented on web/src/utils/Cryption.ts
> +  const _key = CryptoJS.enc.Utf8.parse(keyValue);
Expecting promise to await this task.

2024-04-20 00:27 UTC, mertgvcn commented
Alles gut :

- Database ile bağlantısı olmayan Models klasörü artık NonPersistentModels. Data annotationslarda kaldırıldı.
- Crypto fonksiyonları artık async
- Validation error için çıkan toast messagelar kaldırıldı
- Button spam problemleri giderildi (artık dalga geçemezsin!)
- Bazı yerlerde kod düzenlemeleri yapıldı.

2024-04-20 12:49 UTC, immrlolled requested changes

2024-04-20 12:49 UTC, immrlolled commented on Services/AuthenticationService.cs
> +        var emailExists = await EmailExistsAsync(new EmailExistsRequest() { Email = request.Email });
bu checki yapmana gerek yok. bunu manipule debilirler. backende gonder direk forgot password requesti arkada baksin yoksa email yollamasin.

2024-04-20 12:49 UTC, immrlolled commented on web/src/components/Forms/ForgotPasswordForm/ForgotPassword.tsx
> +          error: <b>Email could not sent!</b>,
erroru kullaniciya bildirmen profesyonel degil kendi icinde exceptionu yakala ve loglamak lazim

2024-04-20 13:32 UTC, immrlolled approved these changes

2024-04-20 13:32 UTC, merged